### ISSUE TITLE
tasks for configuring a certain database such as `configureForPostgres` doesn't work

### ISSUE THREAD

**Issue by fnaranjo-vmw** [cloudfoundry/jdbctestapp#2]
Running `./gradlew configureForPostgres`, `./gradlew configureForMysql` or `./gradlew configureForSQLServer` always fail with error:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/root/workspace/csb/jdbctestapp/build.gradle.kts' line: 19

* What went wrong:
src/main/resources/db/migration/V1__Create_users.sql

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

However, after manually creating the `src/main/resources/db/migration/` folder and copying the template for the desired database it worked. I believe `build.gradle.kts` is implemented in such a way that it tries to check the content of the `migration` folder, even when running the configuring tasks (while the folder doesn't exist yet).

I believe this is a bug, since it makes it impossible to use the configure tasks.
Most probably the bug passed unnoticed by @jhvhs when he introduced the logic in [this commit](https://github.com/cloudfoundry/jdbctestapp/commit/04a0e43dbf07b2843a8fb781f8ee00ff04351253)
because he already had the `migration` folder in place making all tasks "apparently work as expected".

**Comment by jhvhs** [comment]
I am unable to reproduce. What version of Java is being used? 
Here's the output using Java 17:
```
% ./gradlew configureForPostgres
Starting a Gradle Daemon, 1 busy and 1 incompatible Daemons could not be reused, use --status for details

BUILD SUCCESSFUL in 6s
1 actionable task: 1 executed

% cat src/main/resources/db/migration/V1__Create_users.sql
create table users
(
    id   serial
        constraint table_name_pk
            primary key,
    name varchar(255) not null
)

% ./gradlew configureForMysql

BUILD SUCCESSFUL in 7s
1 actionable task: 1 executed

% cat src/main/resources/db/migration/V1__Create_users.sql
create table users
(
    id   int auto_increment
        primary key,
    name varchar(255) not null
);

% ./gradlew configureForSQLServer

BUILD SUCCESSFUL in 713ms
1 actionable task: 1 executed
jdbctestapp % cat src/main/resources/db/migration/V1__Create_users.sql
CREATE TABLE users (
    id INT PRIMARY KEY IDENTITY (1, 1),
    name VARCHAR (50) NOT NULL
)
GO
```
